server:
  port: 9999

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/araruneshwar/CloudServerConfig
          clone-on-start: true
          skipSslValidation: true